name: Manual Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        # Zmenili sme BOARD na orangepi4
        run: ./compile.sh BOARD=orangepi4 BRANCH=current RELEASE=bookworm KERNEL_CONFIGURE=no
