name: Manual Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Armbian Image
        # Nastavujeme COLUMNS, aby Python nespadol na detekcii šírky terminálu
        env:
          COLUMNS: 160
        run: |
          sudo ./compile.sh \
            BOARD=orangepi4 \
            BRANCH=legacy \
            RELEASE=bookworm \
            BUILD_MINIMAL=no \
            BUILD_DESKTOP=no \
            KERNEL_ONLY=no \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=sha,gpg,img \
            EXPERT=yes
